name = "EmiCobbleverse"
author = "SomitadePony"
version = "1.0.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20e197f0629d2e708c7c343b88dcfeec44afec7d35947d00552a6a4360e91c13"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "world/datapacks"
