name = "EmiCobbleverse"
author = "SomitadePony"
version = "1.0.43"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "883ce9d91edd79a551cc049514021fc01374a4ec9d56a6ee41ec94f3e8cfcd99"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "world/datapacks"
