name = "EmiCobbleverse"
author = "SomitadePony"
version = "1.0.44"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "168ae1ddbded4ef2244ca36a0afb3ad9b6469ef602a1428924ad671be331997b"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "world/datapacks"
